CREATE DATABASE IF NOT EXISTS `visualizations`;


CREATE TABLE IF NOT EXISTS `VISUALIZATIONS`
(
  `VISUALIZATIONS_ID`            BIGINT(20)  NOT NULL AUTO_INCREMENT,  
  `ALIAS`                        VARCHAR(30),
  `VISUALIZATION_CONTENT`        VARCHAR(180),
  `IS_FINISHED`                  BOOLEAN,
  `STARTING_POSITION`            INTEGER,
  PRIMARY KEY (`VISUALIZATIONS_ID`)
);